// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Main
{
    public partial class QueryRelationship
    {
        /// <summary>
        /// model input class for QueryRelationship.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"query1")]
            public string Query1 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"query2")]
            public string Query2 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"label")]
            public float Label { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for QueryRelationship.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"query1")]
            public string Query1 { get; set; }

            [ColumnName(@"query2")]
            public string Query2 { get; set; }

            [ColumnName(@"label")]
            public float Label { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("queryRelationship.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            mlContext.GpuDeviceId = 0;
            mlContext.FallbackToCpu = false;
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
